name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build:
    name: grep-static
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
            sudo bash -c "${{ github.workspace }}/build.sh"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: grep-static-v*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
